# Generated by Django 5.1.1 on 2024-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="MarketFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itin_id", models.IntegerField(help_text="Itinerary ID")),
                ("mkt_id", models.IntegerField(help_text="Market ID")),
                (
                    "mkt_coupons",
                    models.IntegerField(help_text="Number of Coupons in the Market"),
                ),
                ("year", models.IntegerField(help_text="Year")),
                ("quarter", models.IntegerField(help_text="Quarter")),
                (
                    "origin_airport_id",
                    models.IntegerField(
                        help_text="Origin Airport, Airport ID 出發機場ID"
                    ),
                ),
                (
                    "origin_airport_seq_id",
                    models.IntegerField(
                        help_text="Origin Airport, Airport Sequence ID. 機場可能會換名字，每換一次就有新的 Seq ID"
                    ),
                ),
                (
                    "origin_city_market_id",
                    models.IntegerField(
                        help_text="Origin Airport, City Market ID 出發城市ID"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="Origin Airport Code 出發機場代號", max_length=3
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(help_text="全都是 US", max_length=3),
                ),
                (
                    "origin_state_fips",
                    models.IntegerField(
                        help_text="Origin Airport, State FIPS Code 出發州的數字代號"
                    ),
                ),
                (
                    "origin_state",
                    models.CharField(
                        help_text="Origin Airport, State Code 出發州的兩碼英文代號",
                        max_length=2,
                    ),
                ),
                (
                    "origin_state_name",
                    models.CharField(
                        help_text="Origin State Name. 完整州名", max_length=100
                    ),
                ),
                (
                    "origin_wac",
                    models.IntegerField(help_text="Origin Airport, World Area Code"),
                ),
                (
                    "dest_airport_id",
                    models.IntegerField(
                        help_text="Destination Airport, Airport ID 抵達機場ID"
                    ),
                ),
                (
                    "dest_airport_seq_id",
                    models.IntegerField(
                        help_text="Destination Airport, Airport Sequence ID 與上面的關係就跟 origin 那邊說明的一樣"
                    ),
                ),
                (
                    "dest_city_market_id",
                    models.IntegerField(
                        help_text="Destination Airport, City Market ID 抵達城市ID"
                    ),
                ),
                (
                    "dest",
                    models.CharField(
                        help_text="Destination Airport Code 抵達機場代號", max_length=3
                    ),
                ),
                (
                    "dest_country",
                    models.CharField(
                        help_text="Destination Country 全都是 US", max_length=3
                    ),
                ),
                (
                    "dest_state_fips",
                    models.IntegerField(
                        help_text="Destination Airport, State FIPS Code 抵達州的數字代號"
                    ),
                ),
                (
                    "dest_state",
                    models.CharField(
                        help_text="Destination Airport, State Code 抵達州的兩碼英文代號",
                        max_length=2,
                    ),
                ),
                (
                    "dest_state_name",
                    models.CharField(
                        help_text="Destination State Name. 完整州名", max_length=100
                    ),
                ),
                (
                    "dest_wac",
                    models.CharField(
                        help_text="Destination Airport, World Area Code", max_length=3
                    ),
                ),
                (
                    "airport_group",
                    models.CharField(
                        help_text="Airport Group 把鄰近的機場組成一個 group 方便一起分析",
                        max_length=100,
                    ),
                ),
                (
                    "wac_group",
                    models.CharField(
                        help_text="World Area Code Group 同上，這個用 wac 進行 group",
                        max_length=100,
                    ),
                ),
                (
                    "tk_carrier_change",
                    models.IntegerField(
                        help_text="Ticketing Carrier Change Indicator (1=Yes) 出票的航空公司是否更改"
                    ),
                ),
                (
                    "tk_carrier_group",
                    models.CharField(
                        help_text="Ticketing Carrier Group 出票的航空公司分組",
                        max_length=100,
                    ),
                ),
                (
                    "op_carrier_change",
                    models.IntegerField(
                        help_text="Operating Carrier Change Indicator (1=Yes) 營運的航空公司是否更改"
                    ),
                ),
                (
                    "op_carrier_group",
                    models.CharField(
                        help_text="Operating Carrier Group 營運的航空公司分組",
                        max_length=100,
                    ),
                ),
                (
                    "rp_carrier",
                    models.CharField(
                        help_text="Reporting Carrier Code 遞交此 survey 的航空公司",
                        max_length=3,
                    ),
                ),
                (
                    "tk_carrier",
                    models.CharField(
                        help_text="Ticketing Carrier Code for On-line Itineraries 出票的航空",
                        max_length=3,
                    ),
                ),
                (
                    "op_carrier",
                    models.CharField(
                        help_text="Operating Carrier Code for On-line Itineraries 營運的航空",
                        max_length=3,
                    ),
                ),
                (
                    "bulk_fare",
                    models.IntegerField(
                        help_text="Bulk Fare Indicator (1=Yes) 是否為團體購入"
                    ),
                ),
                (
                    "passengers",
                    models.IntegerField(help_text="Number of Passengers 乘客人數"),
                ),
                (
                    "mkt_fare",
                    models.FloatField(
                        help_text="Market Fare (ItinYield*MktMilesFlown) 市場票價 = 行程收益率 * 市場飛行里程"
                    ),
                ),
                (
                    "mkt_distance",
                    models.IntegerField(
                        help_text="Market Distance (Including Ground Transport) 移動距離，包含地面交通"
                    ),
                ),
                (
                    "mkt_distance_group",
                    models.IntegerField(
                        help_text="Distance Group, in 500 Mile Intervals 移動距離分組，每 500 miles 一組"
                    ),
                ),
                (
                    "mkt_miles_flown",
                    models.IntegerField(
                        help_text="Market Miles Flown (Track Miles) 飛行距離"
                    ),
                ),
                (
                    "non_stop_miles",
                    models.IntegerField(
                        help_text="Non-Stop Market Miles (Using Radian Measure) 起終點距離"
                    ),
                ),
                (
                    "itin_geo_type",
                    models.IntegerField(
                        help_text="Itinerary Geography Type 整趟行程是否包含美國外州地區 1有 2沒有"
                    ),
                ),
                (
                    "mkt_geo_type",
                    models.IntegerField(
                        help_text="Market Geography Type 指的是這趟行程是否包含美國外州地區 1有 2沒有"
                    ),
                ),
            ],
        ),
    ]
