# Generated by Django 5.1.1 on 2024-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adqp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketfields",
            name="itin_id",
            field=models.BigIntegerField(help_text="Itinerary ID"),
        ),
        migrations.AlterField(
            model_name="marketfields",
            name="mkt_id",
            field=models.BigIntegerField(help_text="Market ID"),
        ),
        migrations.AlterField(
            model_name="marketfields",
            name="origin_airport_id",
            field=models.BigIntegerField(help_text="Origin Airport ID"),
        ),
        migrations.AlterField(
            model_name="marketfields",
            name="origin_airport_seq_id",
            field=models.BigIntegerField(help_text="Origin Airport Sequence ID"),
        ),
        migrations.AlterField(
            model_name="marketfields",
            name="origin_city_market_id",
            field=models.BigIntegerField(help_text="Origin City Market ID"),
        ),
    ]
